---
driver:
  name: dokken
  chef_version: 12.14.89
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: false

platforms:
- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
- name: ubuntu-16.06
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
- name: centos-6.8
  driver:
    image: centos:6.8
    intermediate_instructions:
      - RUN yum install -y initscripts
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-6.6
  driver:
    image: oraclelinux:6.6
- name: oracle-6.7
  driver:
    image: oraclelinux:6.7
- name: oracle-7.1
  driver:
    image: oraclelinux:7.1
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-6
  driver:
    image: debian:6
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install -y procps
- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install -y procps
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
  verifier:
    inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening
