---

driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.3
- name: oracle-6.8
- name: oracle-7.3
- name: debian-7.11
- name: debian-8.6
- name: fedora-24
- name: fedora-25
- name: opensuse-leap-42.1
- name: opensuse-13.2

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
