---
driver:
  name: vagrant

platforms:
- name: ubuntu-14-04
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16-04
  driver_config:
    box: bento/ubuntu-16.04
- name: ubuntu-18-04
  driver_config:
    box: bento/ubuntu-18.04
- name: centos-6
- name: centos-7
- name: oracle-6
- name: oracle-7
- name: debian-9
- name: fedora-27
- name: fedora-28
- name: opensuse-leap-42
- name: amazonlinux-1
  driver_config:
    box: realreadme/amazon2016.09
- name: amazonlinux-2
  driver_config:
    box: stakahashi/amazonlinux2

provisioner:
  name: chef_solo
<% if ENV['CHEF_VERSION'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
<% end %>

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
    attributes:
      kernel_modules_disabled: 1
- name: selinux_enabled
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
  includes:
    - centos-7
  attributes:
    os-hardening:
      security:
        selinux_mode: enforcing
