---
driver:
  name: vagrant

platforms:
- name: ubuntu-16-04
  driver_config:
    box: bento/ubuntu-16.04
- name: ubuntu-18-04
  driver_config:
    box: bento/ubuntu-18.04
- name: centos-7
- name: centos-8
- name: oracle-7
- name: debian-9
- name: debian-10
- name: fedora-28
- name: fedora-29
- name: opensuse-leap-42
- name: amazonlinux-1
  driver_config:
    box: realreadme/amazon2016.09
- name: amazonlinux-2
  driver_config:
    box: stakahashi/amazonlinux2

provisioner:
  name: chef_zero
<% if ENV['CINC_VERSION'] %>
  product_version: <%= ENV['CINC_VERSION'] %>
<% end %>
  download_url: https://omnitruck.cinc.sh/install.sh

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
    attributes:
      kernel_modules_disabled: 1
