---
AllCops:
  DisplayCopNames: true
  Exclude:
  - vendor/**/*
  - test/**/*
  - metadata.rb
  - Berksfile
Metrics/AbcSize:
  Max: 29
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 10
Style/Documentation:
  Enabled: false
Style/AlignParameters:
  Enabled: true
Style/DotPosition:
  EnforcedStyle: trailing
  Enabled: true
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/Encoding:
  EnforcedStyle: always
  Enabled: true
Style/ExtraSpacing:
  Exclude:
    - attributes/default.rb
Style/HashSyntax:
  Enabled: true
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 10
Style/SpaceAroundOperators:
  Exclude:
    - attributes/default.rb
